[package]
name = "maelstrom"
version = "0.1.0"
authors = ["Chris Bruce <chris@chrisbruce.com>"]
edition = "2018"


[dependencies]
actix-cors = "0.2.0"
actix-rt = "1.0"
actix-web = "2.0"
dotenv = "0.15"
env_logger = "0.7"
serde = "1.0"
serde_json = "1.0"
sqlx = { version = "0.3", default-features = false, features = [ "runtime-tokio", "macros" ] }